on: [push]

jobs:
  hello-world-job:
    name: A job to say hello
    runs-on: ubuntu-latest
    steps:

    - name: Hello world action step
      id: hello
      uses: gabrielrtakeda/hello-world-docker-action@master
      with:
        who_to_greet: 'Gabriel Ramos Takeda'

    # Use the output from the `hello` step
    - name: Get the output time
      run: echo "The time was ${{ steps.hello.outputs.time }}"
