on: [push]

jobs:
  testing-job:
    name: A job testing the Github Actions workflow
    runs-on: ubuntu-latest
    steps:

    - name: Install s3cmd
      run: sudo apt-get install s3cmd

    - name: Run s3cmd
      run: |
        s3cmd \
          --force \
          --access_key=${{ secrets.S3_ACCESS_KEY }} \
          --secret_key=${{ secrets.S3_SECRET_KEY }} \
          get ${{ secrets.S3_URL }}/network-graphql/schema/latest-schema.json dev-schema.json

