on: [push]

jobs:
  testing-job:
    name: A job testing the Github Actions workflow
    runs-on: ubuntu-latest
    steps:

    - name: Install s3cmd
      id: hello
      uses: gabrielrtakeda/hello-world-docker-action@master

    - name: Run s3cmd
      run: s3cmd

