on: [push]

jobs:
  testing-job:
    name: A job testing the Github Actions workflow
    runs-on: ubuntu-latest
    steps:

    - name: Hello world action step
      id: hello
      uses: gabrielrtakeda/hello-world-docker-action@master
      with:
        cmd: >-
          --force \
          --access_key=${{ secrets.S3_ACCESS_KEY }} \
          --secret_key=${{ secrets.S3_SECRET_KEY }} \
          get s3://jusbrasil-deps/network-graphql/schema/latest-schema.json dev-schema.json
