on: [push]

jobs:
  testing-job:
    name: A job testing the Github Actions workflow
    runs-on: ubuntu-latest
    steps:

    - name: Hello world action step
      id: hello
      uses: gabrielrtakeda/hello-world-docker-action@master
      run: s3cmd --help

