on: [push]

jobs:
  testing-job:
    name: A job testing the Github Actions workflow
    runs-on: ubuntu-latest
    steps:

    - name: Hello world action step
      id: hello
      uses: gabrielrtakeda/hello-world-docker-action@master
      with:
        access_key: 'my_super_secret_access_key'
        secret_key: 'my_super_secret_secret_key'
        cmd: 'get http://s3.io'
